/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototipobackoffice;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author alvaro.montero
 */
public class AltaOrdenes extends javax.swing.JFrame {

    /**
     * Creates new form Altaordenes
     */
    public AltaOrdenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBICEntidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtContrapartida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtBICContrapartida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDivisa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboSentido = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboMensaje = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtCorresponsalPropio = new javax.swing.JTextField();
        txtCuentaCorresponsalPropio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtCorresponsalAjeno = new javax.swing.JTextField();
        txtCuentaCorresponsalAjeno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtFechaValor = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("(*) BIC Entidad:");

        txtBICEntidad.setText("BSCHESMMXXX");
        txtBICEntidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBICEntidadActionPerformed(evt);
            }
        });

        jLabel3.setText("(*) Contrapartida:");

        jLabel4.setText("BIC Contrapartida:");

        txtBICContrapartida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBICContrapartidaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBICContrapartidaKeyReleased(evt);
            }
        });

        jLabel5.setText("(*) Sentido:");

        jLabel6.setText("(*) Importe:");

        jLabel7.setText("(*) Divisa:");

        txtDivisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDivisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDivisaKeyReleased(evt);
            }
        });

        jLabel8.setText("(*) Fecha valor:");

        jComboSentido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cobro", "Pago " }));
        jComboSentido.setSelectedIndex(1);
        jComboSentido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboSentidoActionPerformed(evt);
            }
        });

        jLabel13.setText("(*) Tipo de Mensaje:");

        jComboMensaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MT103", "MT202", "" }));
        jComboMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMensajeActionPerformed(evt);
            }
        });

        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton2.setText("BORRAR DATOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setText("ALTA DE ORDENES:");

        jLabel17.setText("(*) Corresponsal Propio:");

        jLabel18.setText("Cuenta Corresponsal Propio:");

        txtCorresponsalPropio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorresponsalPropioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorresponsalPropioKeyReleased(evt);
            }
        });

        txtCuentaCorresponsalPropio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuentaCorresponsalPropioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuentaCorresponsalPropioKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorresponsalPropio, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(txtCuentaCorresponsalPropio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCorresponsalPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuentaCorresponsalPropio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Corresponsal Propio", jPanel2);

        txtCorresponsalAjeno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorresponsalAjenoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCorresponsalAjenoKeyReleased(evt);
            }
        });

        txtCuentaCorresponsalAjeno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCuentaCorresponsalAjenoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCuentaCorresponsalAjenoKeyReleased(evt);
            }
        });

        jLabel15.setText("(*) Corresponsal Ajeno:");

        jLabel16.setText("Cuenta Corresponsal Ajeno:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorresponsalAjeno, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(txtCuentaCorresponsalAjeno))
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txtCorresponsalAjeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCuentaCorresponsalAjeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Corresponsal Ajeno", jPanel3);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel9.setText("Los campos marcados con (*) son obligatorios.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel14))
                                .addGap(10, 10, 10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(63, 63, 63))
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtImporte, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                    .addComponent(txtDivisa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFechaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBICEntidad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboSentido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(btnAceptar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                        .addComponent(jComboMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(73, 73, 73)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addGap(93, 93, 93)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtContrapartida, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(txtBICContrapartida)))
                                    .addComponent(jLabel9))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBICEntidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtContrapartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtBICContrapartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboSentido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(jComboMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAceptar)
                                    .addComponent(jButton2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtFechaValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
        try {
            String bic_Entidad = "BSCHESMMXXX";
            String tipo_Orden = "Individual";
            String ref_Orden = "";
            String contrapartida = txtContrapartida.getText();
            String bic_Contrapartida = txtBICContrapartida.getText();
            String sentido = jComboSentido.getSelectedItem().toString();
            double importe = Double.parseDouble(txtImporte.getText());
            String divisa = txtDivisa.getText();
            Date fecha_Entrada = new java.util.Date();
            Date fecha_Valor = new Date(txtFechaValor.getSelectedDate().getTimeInMillis());
            Date fecha_liberacion = new Date(txtFechaValor.getSelectedDate().getTimeInMillis());
            Date fecha_Liquidacion = new Date(txtFechaValor.getSelectedDate().getTimeInMillis());
            String corresponsal_Propio = txtCorresponsalPropio.getText();
            String cuenta_Corresponsal_Propio = txtCuentaCorresponsalPropio.getText();
            String corresponsal_Ajeno = txtCorresponsalAjeno.getText();
            String cuenta_Corresponsal_Ajeno = txtCuentaCorresponsalAjeno.getText();
            String tipo_Mensaje = jComboMensaje.getSelectedItem().toString();
            String estado = "No liberada";
            Orden ordenInsertar = new Orden(bic_Entidad, tipo_Orden, ref_Orden, contrapartida, sentido, importe, divisa, fecha_Entrada, fecha_Valor, fecha_Liquidacion, fecha_liberacion, corresponsal_Propio, cuenta_Corresponsal_Propio, bic_Contrapartida, corresponsal_Ajeno, cuenta_Corresponsal_Ajeno, tipo_Mensaje);

            new BackofficeDao().insertarOrden(ordenInsertar);
            dispose();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El campo importe debe contener un valor estrictamente numerico", "ATENCION", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_btnAceptarActionPerformed


    private void jComboMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMensajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMensajeActionPerformed

    private void jComboSentidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboSentidoActionPerformed
        // TODO add your handling code here:
        if (jComboSentido.getSelectedItem().equals("Cobro")) {
            jComboMensaje.setSelectedItem("");
        }
    }//GEN-LAST:event_jComboSentidoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtBICContrapartida.setText("");
        txtBICEntidad.setText("BSCHESMMXXX");
        txtContrapartida.setText("");
        txtCorresponsalAjeno.setText("");
        txtCorresponsalPropio.setText("");
        txtCuentaCorresponsalAjeno.setText("");
        txtCuentaCorresponsalPropio.setText("");
        txtDivisa.setText("");
        txtFechaValor.setText("");
        txtImporte.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDivisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDivisaKeyPressed
        // TODO add your handling code here:
        if (txtDivisa.getText().length() >= 3) {
            txtDivisa.setText(txtDivisa.getText().substring(0, 3));
        }
    }//GEN-LAST:event_txtDivisaKeyPressed

    private void txtDivisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDivisaKeyReleased
        // TODO add your handling code here:
        if (txtDivisa.getText().length() >= 3) {
            txtDivisa.setText(txtDivisa.getText().substring(0, 3));
        }
    }//GEN-LAST:event_txtDivisaKeyReleased

    private void txtBICContrapartidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBICContrapartidaKeyPressed
        // TODO add your handling code here:
        if (txtBICContrapartida.getText().length() >= 11) {
            txtBICContrapartida.setText(txtBICContrapartida.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtBICContrapartidaKeyPressed

    private void txtBICContrapartidaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBICContrapartidaKeyReleased
        // TODO add your handling code here:
        if (txtBICContrapartida.getText().length() >= 11) {
            txtBICContrapartida.setText(txtBICContrapartida.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtBICContrapartidaKeyReleased

    private void txtCorresponsalPropioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorresponsalPropioKeyPressed
        // TODO add your handling code here:
        if (txtCorresponsalPropio.getText().length() >= 11) {
            txtCorresponsalPropio.setText(txtCorresponsalPropio.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtCorresponsalPropioKeyPressed

    private void txtCorresponsalPropioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorresponsalPropioKeyReleased
        // TODO add your handling code here:
        if (txtCorresponsalPropio.getText().length() >= 11) {
            txtCorresponsalPropio.setText(txtCorresponsalPropio.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtCorresponsalPropioKeyReleased

    private void txtCuentaCorresponsalPropioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaCorresponsalPropioKeyPressed
        // TODO add your handling code here:
        if (txtCuentaCorresponsalPropio.getText().length() >= 35) {
            txtCuentaCorresponsalPropio.setText(txtCuentaCorresponsalPropio.getText().substring(0, 35));
        }
    }//GEN-LAST:event_txtCuentaCorresponsalPropioKeyPressed

    private void txtCuentaCorresponsalPropioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaCorresponsalPropioKeyReleased
        // TODO add your handling code here:
        if (txtCuentaCorresponsalPropio.getText().length() >= 35) {
            txtCuentaCorresponsalPropio.setText(txtCuentaCorresponsalPropio.getText().substring(0, 35));
        }
    }//GEN-LAST:event_txtCuentaCorresponsalPropioKeyReleased

    private void txtCorresponsalAjenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorresponsalAjenoKeyPressed
        // TODO add your handling code here:
        if (txtCorresponsalAjeno.getText().length() >= 11) {
            txtCorresponsalAjeno.setText(txtCorresponsalAjeno.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtCorresponsalAjenoKeyPressed

    private void txtCorresponsalAjenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorresponsalAjenoKeyReleased
        // TODO add your handling code here:
        if (txtCorresponsalAjeno.getText().length() >= 11) {
            txtCorresponsalAjeno.setText(txtCorresponsalAjeno.getText().substring(0, 11));
        }
    }//GEN-LAST:event_txtCorresponsalAjenoKeyReleased

    private void txtCuentaCorresponsalAjenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaCorresponsalAjenoKeyPressed
        // TODO add your handling code here:
        if (txtCuentaCorresponsalAjeno.getText().length() >= 35) {
            txtCuentaCorresponsalAjeno.setText(txtCuentaCorresponsalAjeno.getText().substring(0, 35));
        }
    }//GEN-LAST:event_txtCuentaCorresponsalAjenoKeyPressed

    private void txtCuentaCorresponsalAjenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuentaCorresponsalAjenoKeyReleased
        // TODO add your handling code here:
        if (txtCuentaCorresponsalAjeno.getText().length() >= 35) {
            txtCuentaCorresponsalAjeno.setText(txtCuentaCorresponsalAjeno.getText().substring(0, 35));
        }
    }//GEN-LAST:event_txtCuentaCorresponsalAjenoKeyReleased

    private void txtBICEntidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBICEntidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBICEntidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaOrdenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaOrdenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaOrdenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaOrdenes.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaOrdenes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboMensaje;
    private javax.swing.JComboBox<String> jComboSentido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField txtBICContrapartida;
    private javax.swing.JTextField txtBICEntidad;
    private javax.swing.JTextField txtContrapartida;
    private javax.swing.JTextField txtCorresponsalAjeno;
    private javax.swing.JTextField txtCorresponsalPropio;
    private javax.swing.JTextField txtCuentaCorresponsalAjeno;
    private javax.swing.JTextField txtCuentaCorresponsalPropio;
    private javax.swing.JTextField txtDivisa;
    private datechooser.beans.DateChooserCombo txtFechaValor;
    private javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
